export const DIRECTIONS = {
  DOWN: "DOWN",
  LEFT: "LEFT",
  RIGHT: "RIGHT",
  UP: "UP"
};

export const KEY_LOOKUP = {
  ArrowDown: DIRECTIONS.DOWN,
  ArrowLeft: DIRECTIONS.LEFT,
  ArrowRight: DIRECTIONS.RIGHT,
  ArrowUp: DIRECTIONS.UP
};

export const INVALID_DIRECTION_MAP = {
  [DIRECTIONS.DOWN]: DIRECTIONS.UP,
  [DIRECTIONS.LEFT]: DIRECTIONS.RIGHT,
  [DIRECTIONS.RIGHT]: DIRECTIONS.LEFT,
  [DIRECTIONS.UP]: DIRECTIONS.DOWN
};

export const CHANGE_DIRECTION = "CHANGE_DIRECTION";
export const MOVE_SNAKE = "MOVE_SNAKE";
export const NEW_GAME = "NEW_GAME";
